apiVersion: v1
kind: Service
metadata:
  name: seclock-app-svc
spec:
  type: NodePort              # simplest choice with no cloud load balancer (no EKS)
  selector:
    app: seclock-app
  ports:
    - port: 80
      targetPort: 8080        # must match containerPort in deployment.yaml
      nodePort: 30080          # choose any free port in the 30000-32767 range
